services:
  - type: web
    name: brochuregen-backend-docker
    env: docker
    repo: https://github.com/donmckinney12/brochuregen
    rootDirectory: backend
    plan: free
    region: oregon
    healthCheckPath: /api/v1/command/pulse
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_FRONTEND_API
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./sql_app.db
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000
